### ISSUE TITLE
File permissions incorrect

### ISSUE THREAD

**Issue by thernstig** [ansible/role-secure-docker-daemon#2]
See https://docs.docker.com/engine/security/https/#create-a-ca-server-and-client-keys-with-openssl

generate_client_certs.yml and generate_server_certs.yml does not set the same permission as specified in the above link.

0400 should be set on all keys
0444 should be set on all certs

As such, both .yml files need to split the file permission step into two tasks to handle this.

**Comment by bk203** [comment]
So like this, if i correctly understand the problem:

generate_client_certs.yml
```
- name: Set file permissions for keys
  file:
    path: "{{ dds_client_cert_path }}/{{ item }}"
    mode: 0400
  with_items:
    - key.pem

- name: Set file permissions for certificates
  file:
    path: "{{ dds_client_cert_path }}/{{ item }}"
    mode: 0444
  with_items:
    - ca.pem
    - cert.pem
```

generate_server_certs.yml
```
- name: Set file permissions for keys
  file:
    path: "{{ dds_server_cert_path }}/{{ item }}"
    mode: 0400
  with_items:
    - server-key.pem

- name: Set file permissions for certificates
  file:
    path: "{{ dds_server_cert_path }}/{{ item }}"
    mode: 0444
  with_items:
    - ca.pem
    - server-cert.pem
```
